### ISSUE TITLE
BUG | fast-crc32c does not work when running on a flex GAE instance

### ISSUE THREAD

**Issue by louisgv** [googleapis/nodejs-storage#1445]
Thanks for stopping by to let us know something could be better!

1) Is this a client library issue or a product issue?

- client library

2) Did someone already solve this?

- no

3) Do you have a support contract?

- no

#### Environment details

  - OS: GAE Flex (app.yaml included below)
  - Node.js version: ">=12"
  - npm version: GAE's included version
  - `@google-cloud/storage` version: "^5.8.1"

```
runtime: nodejs

env: flex
network:
  session_affinity: true

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
```

#### Steps to reproduce

  1. Implement the stream download example
  2. Install `fast-crc32c`
  3. Deploy to GAE

#### Error

> Error: no CRC-32C implementation is available

#### Proposed solution

+ @stephenplusplus can you please review https://github.com/ashi009/node-fast-crc32c/issues/21 . Even firebase-tools also resorted to remove it recently: https://github.com/firebase/firebase-tools/pull/3249
+ Replace `hash-stream-validation` with `node-rs/crc32`
