### ISSUE TITLE
Memory leak in createReadStream when destroy() is called on resulting stream and validation is set to true

### ISSUE THREAD

**Issue by jpambrun** [googleapis/nodejs-storage#2010]
Memory leak in createReadStream when destroy() is called on resulting stream and validation is set to true. This could occur when 1) the required data could be before the end of the file and reading to completion is not required, or 2) when a downstream client is disconnected or has navigated away.

#### Environment details

  - OS: Linux
  - Node.js version: v18.6.0
  - npm version: 8.14.0
  - `@google-cloud/storage` version: 6.2.3

#### Steps to reproduce

  1. Start GCS simulator using provided docker compose. (this **also occurs in real GCS**, simulator is just for convenience)
  2. Run supplied script with `validation: true`
  3. Notice increasing memory usage, up to 700mb+
  4. Re-run supplied script with `validation: false`
  5. Notice constant low memory usage.

## docker compose setup
``` yaml
version: "3.9"  # optional since v1.27.0
services:
  google-cloud-storage-http2:
    image: caddy:2.4.5
    ports:
      - "4443:443"
    entrypoint: ["sh", "-c", 'echo "$$CADDY_CONFIG" > Caddyfile && cat Caddyfile && caddy run']
    environment:
      CADDY_CONFIG: >
          {
            auto_https disable_redirects
            local_certs
          }
          localhost {
            log
            reverse_proxy {
                    to http://google-cloud-storage:80
                    header_down Location (http://\[::\]:80)(.*) https://localhost:4443$$2
            }
          }
  google-cloud-storage:
    image: fsouza/fake-gcs-server:latest
    entrypoint: ["sh", "-c", "mkdir -p /data && mkdir -p /preload/vision-poc && touch /preload/vision-poc/.keep && /bin/fake-gcs-server -scheme http -port 80 -data /preload -filesystem-root /data"]
    ports:
      - "4080:80"
```

## script
``` js
import { Storage } from "@google-cloud/storage";
import stream from "stream";
import crypto from "crypto";
import { promisify } from "util";
import pump from "pump";
import process from "process";

const pPump = promisify(pump);
import pLimit from "p-limit";

process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;

const buf = crypto.randomBytes(1024 * 1024 * 2);
const bucketName = "vision-poc";
const fileName = "file.txt";
const storage = new Storage({ apiEndpoint: "https://localhost:4443", projectId: "fake-project-id" });

const myBucket = storage.bucket(bucketName);
const file = myBucket.file(fileName);

async function upload() {
  const passthroughStream = new stream.PassThrough();
  passthroughStream.write(buf);
  passthroughStream.end();
  await pPump(passthroughStream, file.createWriteStream());
}

function download() {
  return new Promise(async (resolve, reject) => {
    const res = await file.createReadStream({ validation: true });
    const chunks = [];
    res.on("data", (chunk) => {
      chunks.push(chunk);
      const bytesSoFar = chunks.reduce((acc, cur) => acc + cur.length, 0);

      if (bytesSoFar > 1024 * 1024 * 1) {
        chunks.length = 0
        res.destroy(); // <--- HERE I don't need more data, or downstream client is gone
        console.log(process.memoryUsage().rss / 1024 / 1024);
        resolve();
      }
    });
    res.on("error", (err) => {
      console.log(err);
      reject(err);
    });
    res.on("end", () => {
      console.log("end"); // not reached
    });
  });
}

// main
(async () => {
  await upload().catch(console.error);

  const limit = pLimit(100);

  const promises = [];
  for (let i = 0; i < 2000; i++) {
    const promise = limit(download);
    promises.push(promise);
  }

  await Promise.all(promises).catch(console.error);

  setInterval(() => {
    console.log(process.memoryUsage().rss / 1024 / 1024);
  }, 1000);
})();

```
