### ISSUE TITLE
Missing / undocumented feature in File.getSignedUrl()

### ISSUE THREAD

**Issue by OscarHedeby** [googleapis/nodejs-storage#2410]
The error seems trivial to solve. "method" is missing on the GetSignedUrlConfig type. 

Without this it's impossible to generate a signed url that can be used over CORS.

#### Environment details

  - OS: MacOS
  - Node.js version: v18.19.0
  - npm version: v10.2.3
  - `@google-cloud/storage` version: v7.7.0

#### Steps to reproduce

```
const storage = new Storage();
const bucket = storage.bucket(process.env.GCS_BUCKET);
const file = bucket.file(`test.png`);
file.getSignedUrl({
    version: "v4",
    method: "PUT", <---- error on this line
    action: "write",
    expires: Date.now() + 15 * 60 * 1000, // 15 minutes
});
```

**Comment by ddelgrosso1** [comment]
Hi @OscarHedeby it is not actually missing, it is under `config.action`. For a put you want to use the value `write`. Please see the docs [here](https://googleapis.dev/nodejs/storage/latest/File.html#getSignedUrl).

**Comment by OscarHedeby** [comment]
Then I think there is a problem with the implementation. It does not look like it allows CORS when using write.

```
const [url] = await file.getSignedUrl({
  version: "v4",
  action: "write",
  expires: Date.now() + 15 * 60 * 1000, // 15 minutes
});
```
I Get this error with the config above, but if I change to this it works:
```
const [url] = await file.getSignedUrl({
  version: "v4",
  method: "PUT", // Error in the library type definition
  action: "write",
  expires: Date.now() + 15 * 60 * 1000, // 15 minutes
});
```

Error on the client when uploading without "PUT" method:
![Screenshot 2024-02-26 at 17 01 43](https://github.com/googleapis/nodejs-storage/assets/43882239/74ec2bbc-dec3-4a23-b6ca-297fa6b49fc2)

**Comment by ddelgrosso1** [comment]
@OscarHedeby can you provide the headers being sent in the request and / or a sample of the code used to make the request?

**Comment by OscarHedeby** [comment]
Sure, it's just a simple axios put. The url is the one provided by the function with no alterations.

```
await axios.put(url, file, {
  onUploadProgress: (progressEvent) => {
    console.log(
      (progressEvent.loaded / progressEvent.total) * 100
    );
  },
});
```

Request:
```
PUT /hobby-processing/6563fa84-b354-4559-aa6f-ded8e4d75c0c.png
Accept: application/json, text/plain, */*
Content-Type: application/x-www-form-urlencoded
Origin: http://127.0.0.1:3000
Referer: http://127.0.0.1:3000/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Safari/605.1.15
Query string params:
X-Goog-Algorithm: GOOG4-RSA-SHA256
X-Goog-Credential: oscar-mbp@..../auto/storage/goog4_request
X-Goog-Date: 20240227T084625Z
X-Goog-Expires: 900
X-Goog-SignedHeaders: host
X-Goog-Signature: 755f5e3d....172f
```

**Comment by ddelgrosso1** [comment]
@OscarHedeby one other thing, can you share the bucket configuration as it pertains to CORS?

**Comment by OscarHedeby** [comment]
Sure, here is the 

```
---
cors_config:
- maxAgeSeconds: 3600
  method:
  - GET
  - HEAD
  - PUT
  - POST
  - DELETE
  origin:
  - http://*
  - https://*
  - http://localhost:3000
  responseHeader:
  - '*'
creation_time: 2024-02-25T18:21:57+0000
default_storage_class: STANDARD
location: EUROPE-NORTH1
location_type: region
metageneration: 6
name: hobby-processing
public_access_prevention: enforced
storage_url: gs://hobby-processing/
uniform_bucket_level_access: true
update_time: 2024-02-25T21:30:27+0000
```
